name: Github Pages
on: [push]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2 # repo checkout

      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.57

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-emscripten
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build # build
        run: ./scripts/build.sh -er # release, skip emsdk

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist/'
          retention-days: 7

      - name: Deploy
        uses: actions/deploy-pages@v2